# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.cache/wt [current_project]
set_property parent.project_path /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_0/design_1_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /es_home/aali/VivadoProjects/session_5/sub_system_axi_design/sub_system_axi_design.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
