# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.cache/wt [current_project]
set_property parent.project_path /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
add_files /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_ds_1/system_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_ds_1/system_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/sources_1/bd/system/hdl/system_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /es_home/aali/VivadoProjects/project1/edt_zc702/edt_zc702.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
