// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "axi_stream_counter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic axi_stream_counter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic axi_stream_counter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> axi_stream_counter::ap_ST_st1_fsm_0 = "1";
const sc_lv<32> axi_stream_counter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> axi_stream_counter::ap_const_lv1_1 = "1";
const sc_lv<32> axi_stream_counter::ap_const_lv32_1 = "1";

axi_stream_counter::axi_stream_counter(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_ioackin_counter_output_TREADY );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_ioackin_counter_output_TREADY );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_ioackin_counter_output_TREADY );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_62);
    sensitive << ( ap_start );
    sensitive << ( counter_output_TREADY );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_18 );

    SC_METHOD(thread_ap_sig_ioackin_counter_output_TREADY);
    sensitive << ( counter_output_TREADY );
    sensitive << ( ap_reg_ioackin_counter_output_TREADY );

    SC_METHOD(thread_counterValue_assign_fu_33_p2);
    sensitive << ( counterValue );

    SC_METHOD(thread_counter_output_TDATA);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( counterValue );

    SC_METHOD(thread_counter_output_TDATA_blk_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( counter_output_TREADY );

    SC_METHOD(thread_counter_output_TVALID);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_reg_ioackin_counter_output_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_ioackin_counter_output_TREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    counterValue = "00000000000000000000000000000000";
    ap_reg_ioackin_counter_output_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "axi_stream_counter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, counter_output_TDATA, "(port)counter_output_TDATA");
    sc_trace(mVcdFile, counter_output_TVALID, "(port)counter_output_TVALID");
    sc_trace(mVcdFile, counter_output_TREADY, "(port)counter_output_TREADY");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_18, "ap_sig_18");
    sc_trace(mVcdFile, counterValue, "counterValue");
    sc_trace(mVcdFile, counter_output_TDATA_blk_n, "counter_output_TDATA_blk_n");
    sc_trace(mVcdFile, counterValue_assign_fu_33_p2, "counterValue_assign_fu_33_p2");
    sc_trace(mVcdFile, ap_sig_ioackin_counter_output_TREADY, "ap_sig_ioackin_counter_output_TREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_counter_output_TREADY, "ap_reg_ioackin_counter_output_TREADY");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_62, "ap_sig_62");
#endif

    }
    mHdltvinHandle.open("axi_stream_counter.hdltvin.dat");
    mHdltvoutHandle.open("axi_stream_counter.hdltvout.dat");
}

axi_stream_counter::~axi_stream_counter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void axi_stream_counter::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_counter_output_TREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
            if (!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_counter_output_TREADY.read()))) {
                ap_reg_ioackin_counter_output_TREADY = ap_const_logic_0;
            } else if (ap_sig_62.read()) {
                ap_reg_ioackin_counter_output_TREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_counter_output_TREADY.read())))) {
        counterValue = counterValue_assign_fu_33_p2.read();
    }
}

void axi_stream_counter::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_counter_output_TREADY.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void axi_stream_counter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void axi_stream_counter::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_counter_output_TREADY.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void axi_stream_counter::thread_ap_return() {
    ap_return = ap_const_lv32_0;
}

void axi_stream_counter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void axi_stream_counter::thread_ap_sig_18() {
    ap_sig_18 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void axi_stream_counter::thread_ap_sig_62() {
    ap_sig_62 = (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_logic_1, counter_output_TREADY.read()));
}

void axi_stream_counter::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_18.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void axi_stream_counter::thread_ap_sig_ioackin_counter_output_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_counter_output_TREADY.read())) {
        ap_sig_ioackin_counter_output_TREADY = counter_output_TREADY.read();
    } else {
        ap_sig_ioackin_counter_output_TREADY = ap_const_logic_1;
    }
}

void axi_stream_counter::thread_counterValue_assign_fu_33_p2() {
    counterValue_assign_fu_33_p2 = (!counterValue.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(counterValue.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void axi_stream_counter::thread_counter_output_TDATA() {
    counter_output_TDATA = (!counterValue.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(counterValue.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void axi_stream_counter::thread_counter_output_TDATA_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        counter_output_TDATA_blk_n = counter_output_TREADY.read();
    } else {
        counter_output_TDATA_blk_n = ap_const_logic_1;
    }
}

void axi_stream_counter::thread_counter_output_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_counter_output_TREADY.read()))) {
        counter_output_TVALID = ap_const_logic_1;
    } else {
        counter_output_TVALID = ap_const_logic_0;
    }
}

void axi_stream_counter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void axi_stream_counter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"counter_output_TDATA\" :  \"" << counter_output_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"counter_output_TVALID\" :  \"" << counter_output_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"counter_output_TREADY\" :  \"" << counter_output_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

